databrickslabs/migrate

dbclient/parser.py
export_db.py

Please merge into master if OK, thx.

Added support for multiple emails

---

dbclient/dbclient.py

This PR will distinguish this scripts from other Python scripts, that run against Databricks REST API

Add usage tracking through dedicated User-Agent header

---

dbclient/HiveClient.py

This PR is simply importing RE that is being used by the script.
Issue https://github.com/databrickslabs/migrate/issues/41

Import RE on HiveClient

---

jumpbox/README.md

Add how to create an instance section to the jumpbox README file

---

dbclient/ClustersClient.py
dbclient/HiveClient.py
dbclient/JobsClient.py
dbclient/ScimClient.py
dbclient/SecretsClient.py
dbclient/TableACLsClient.py
dbclient/dbclient.py
logging_utils.py
pipeline/pipeline.py
tasks/tasks.py
wmconstants.py

**Description**
1. Updated error handling for other clients - ClustersClient, HiveClient, JobsClient, ScimClient, SecretsClient
2. Added logic to exclude error logging for expected errors - Resource_Already_Exists (when imports are done more than once)
3. Fixed the logic such that we can skip task before error handling check happens
**Testing**
Manually tested export and import

Added error handling for more clients

---

migration_pipeline.py
tasks/tasks.py
validate/json_diff.py
validate/json_diff_test.py
validate_pipeline.sh
validation_metastores.log
validation_notebooks.log

This PR onboard all object types to validation pipeline.
`$ python3 -m unittest validate/json_diff_test.py`
```
(PLAT-45083) ~/migrate $ ./validate_pipeline.sh E20211209153920 E20211209154049
Using the session id: V20211216230340
Start validate-instance_profile
############################# validate-instance_profile #################################
---------------- Compare logs/E20211209153920/instance_profiles.log <-> logs/E20211209154049/instance_profiles.log ---------------------
Object counts 1 <-> 1
No diff found.
validate-instance_profile Completed. Total time taken: 0:00:00.000543
Start validate-users
############################# validate-users #################################
---------------- Compare logs/E20211209153920/users.log <-> logs/E20211209154049/users.log …
```

Onboard all object types

---

README.md
checkpoint_service.py
dbclient/HiveClient.py
dbclient/MLFlowClient.py
dbclient/WorkspaceClient.py
dbclient/__init__.py
dbclient/parser.py
export_db.py
import_db.py
logging_utils.py
migration_pipeline.py
setup.py
tasks/tasks.py
test/thread_safe_writer_test.py
thread_safe_writer.py
wmconstants.py

Notable additions:
- Added parallel capabilities on notebook exports and imports
- MLflow experiment export/import is supported (Other ML objects will be supported in later batch)
How is this tested?:
```
python3 migration_pipeline.py --profile mwc_src --export-pipeline --use-checkpoint --num-parallel 20
.....
.....
Export finished successfully. Session Id: M20220210152603
2022-02-10,15:40:42;INFO;finish_export Completed. Total time taken: 0:00:00.016202
```
```
python3 migration_pipeline.py --profile mwc_dst --import-pipeline --use-checkpoint --num-parallel 20 --session M20220210152603
......
.....
Successfull notebook run with notebook_output: {"total_num_acls": 15, "num_sucessfully_executed": 15, "num_execution_errors": 0, "num_error_entries_acls": 0} …
```

Tiger merge 2022-02-10

---

README.md
dbclient/MLFlowClient.py
dbclient/WorkspaceClient.py
export_db.py
tasks/tasks.py
test/thread_safe_writer_test.py
thread_safe_writer.py

This is a set of changes that were patched into tiger merge PR which will be merged into master directly. 
We track the same of changes and merge to tiger branch to prevent the diverges of tiger branch from master branch
1. remove concurrency on --workspace
2. use threading.Lock() instead of queue

Patch changes made to master branch

---

migration_pipeline.py

Port https://github.com/databrickslabs/migrate/pull/112/files to master

Tiger merge 2022 02 22

---

dbclient/WorkspaceClient.py

Fixes https://github.com/databrickslabs/migrate/issues/119

Fix user_home export

---

dbclient/WorkspaceClient.py
export_db.py
logging_utils.py

Porting https://github.com/databrickslabs/migrate/pull/123

Port Fix2 of export-user-home

---

dbclient/dbclient.py

Context: https://github.com/databrickslabs/migrate/issues/126

[Issues-126] throw on 429 error code

---

dbclient/WorkspaceClient.py
dbclient/dbclient.py

Error code and shared dir

---

dbclient/WorkspaceClient.py

If exception is raised in threads, it should be propagated to the main processor and exits
https://github.com/databrickslabs/migrate/issues/126
tested that too many requests 429 error is properly thrown and exits the program:
```
python3 migration_pipeline.py --profile mwc_dst --import-pipeline --use-checkpoint --num-parallel 10 --skip-tasks 'metastore' 'metastore_table_acls'  'jobs' 'instance_pools' 'clusters' 'secrets' --session M20220309173445
File "/Users/kevinkim/migrate/dbclient/WorkspaceClient.py", line 728, in _file_upload_helper
resp_upload = self.post(WS_IMPORT, nb_input_args)
File "/Users/kevinkim/migrate/dbclient/dbclient.py", line 223, in post
return self.http_req('post', endpoint, json_params, version, print_json, files_json)
File …
```

[PLAT-50563] threads should raise exception

---

dbclient/WorkspaceClient.py

Back porting https://github.com/databrickslabs/migrate/pull/132

threads should raise exception

---

dbclient/MLFlowClient.py
dbclient/WorkspaceClient.py
dbclient/dbclient.py
dbclient/parser.py
export_db.py
import_db.py
migration_pipeline.py
test/thread_safe_writer_test.py
test/threading_utils_test.py
threading_utils.py

Backporting https://github.com/databrickslabs/migrate/pull/142/files
Tested:
```
date; time python3 migration_pipeline.py --profile mwc_src --export-pipeline --use-checkpoint --num-parallel 10 --skip-tasks 'metastore' 'metastore_table_acls'
date; time python3 migration_pipeline.py --profile mwc_dst --import-pipeline --use-checkpoint --num-parallel 10 --skip-tasks 'metastore' 'metastore_table_acls' 'workspace_acls' --session M20220322094645
```

Http retry backport

---

dbclient/dbclient.py
export_db.py
import_db.py
migration_pipeline.py
test_connection.py

Mainly doing this as an exercise to keep up my `git` CLI skills... please let me know if there's anything else I need to do on my end. Thanks!

bugfix for latest version of databricks-cli config (token -> password)

---

dbclient/JobsClient.py

multi-task jobs may have existing_cluster_id per task

---

dbclient/ScimClient.py

Tested with single step: export - import users/groups, successfully imported azure SPNs from one workspace to another.

add Azure SPN import logic to ScimClient

---

dbclient/WorkspaceClient.py

create parent dir for Repo if it does not exist

---

data/notebooks/Export_Table_ACLs.py
data/notebooks/Import_Table_ACLs.py

attempt to fix issue #223 
tested it with customer and it works
however does not get to the root cause and the code would need a bit more massaging?

fix for driver OOM in export of table ACLs

---

README.md

TF Exporter is part of an official product.

Added Terraform Exporter product notice
