databrickslabs/migrate

- README.md
- data/aws_cluster_table_acls.json
- data/notebooks/Export_Table_ACLs.py
- data/notebooks/Import_Table_ACLs.py
- dbclient/TableACLsClient.py
- export_db.py
- import_db.py
Made Table ACLs export work on demo.cloud.databricks.com --table-acls  --debug
- most changes were done to the notebooks: added exception handling to SQL GRANTS
- added JSON result to notebooks and display in export and import calls
- added retry logic to notebook job run polling, as it would at times die
- import has just been done to e2-demo-migrate-dst.cloud.databricks.com - SQL GRANTS fail, but execute correct otherwise
- added much more detailed docu directly inside the notebooks - they can be used stand alone
- docu for readme not added yet, it will be mostly I shortened version of the docu I added to the notebooks (cell1)
> Table ACLs tested --table-acls  --debug

- dbclient/dbclient.py
- dbclient/parser.py
- dbclient/test/dbclient_test.py
- export_db.py
- import_db.py
- migration_pipeline.py
- tasks/tasks_test.py
- test_connection.py
Pause migration when expired token is detected. Wait until the token is renewed by runner and resume the migration pipeline.
Unittests
```
$ python3 -m unittest dbclient/test/dbclient_test.py
$ python3 -m unittest pipeline/pipeline_test.py
$ python3 -m unittest tasks/tasks_test.py
```
Locally tested by running:
```
$ python3 migration_pipeline.py --profile src
2021-11-15,23:03:07;INFO;Start `export_users_and_groups`
Migration paused due to expired token. Trying to renew...
No new token found. Please renew token by running:
$ databricks configure --token --profile src
Will try again in 120 seconds.
Migration paused due to expired token. Trying to renew...
New token found. Migration resumed.
2021-11-15,23:05:17;INFO;Complete Users Export Time: 0:02:10.097683
```
> Renew token

- dbclient/TableACLsClient.py
- migration_pipeline.py
It turned out that not all workspaces (for legacy or w.e. reasons) necessarily have the "admin" folders. So if the invoker is dbadmin user, we create the tmp directory on the top level directory
> Make it work for dbadmin user in all cases

- data/aws_cluster.json
- dbclient/ClustersClient.py
- dbclient/SecretsClient.py
- dbclient/TableACLsClient.py
- dbclient/parser.py
- migration_pipeline.py
This PR makes the --cluster-name flag optional by making the downstream tasks launch cluster by itself.
Launch cluster is noop if the the cluster is already up and running.
Manual testing:
```
python3 migration_pipeline.py --profile prod_src_miklos --export-pipeline --use-checkpoint
python3 migration_pipeline.py --profile prod_dst_kevin --import-pipeline --use-checkpoint --session 20211207125516
```
> Make --cluster-name optional

- data/aws_cluster.json
- dbclient/ClustersClient.py
- dbclient/SecretsClient.py
- dbclient/parser.py
- migration_pipeline.py
- tasks/tasks.py
- validate/__init__.py
- validate/json_diff.py
- validate/json_diff_test.py
This PR includes:
Tested
```python3 -m unittest validate/json_diff_test.py```
``` python3 migration_pipeline.py --validate-pipeline --validate-source-session=E20211209153920 --validate-destination-session=E20211209154049
Start validate-instance_profile
######################### validate-instance_profile Start #########################
---------------- Compare logs/E20211209153920/instance_profiles.log <-> logs/E20211209154049/instance_profiles.log ---------------------
Object counts 1 <-> 1
No diff found.
######################### validate-instance_profile Complete ######################
validate-instance_profile Completed. Total time taken: 0:00:00.001716
Start validate-users
######################### validate-users Start #########################
---------------- Compare …
```
> Data integrity validation implementation #2

- setup.py
Added mlflow-skinny and sqlparse to setup.py
`python3 setup.py --install`
Example commands for creating and listing experiments worked after installing:
```
from mlflow.entities import ViewType
from mlflow.tracking import MlflowClient
import mlflow
mlflow.set_registry_uri("databricks://test_shard")
client = MlflowClient()
for name in ["Experiment 1", "Experiment 2"]:
exp_id = client.create_experiment(name)
print(client.list_experiments(view_type=ViewType.ACTIVE_ONLY))
[<Experiment: artifact_location='file:///Users/kevinkim/migrate/mlruns/0', experiment_id='0', lifecycle_stage='active', name='Default', tags={}>, <Experiment: artifact_location='file:///Users/kevinkim/migrate/mlruns/1', ex
periment_id='1', lifecycle_stage='active', name='Experiment 1', tags={}>, <Experiment: …
```
> [PLAT-46716] Add ml python dependency

- dbclient/MLFlowClient.py
- dbclient/__init__.py
- dbclient/parser.py
- export_db.py
- wmconstants.py
usage:
`python3 export_db.py --profile $PROFILE --mlflow_experiments`
Tests:
```
python3 export_db.py --profile dogfood --mlflow_experiments
Exporting MLflow experiments.
2022-01-25,16:53:43;INFO;Complete MLflow Experiments Export Time: 0:00:06.048322
// writes logs/mlflow_experiments.log file (with 3954 items)
{"artifact_location": "dbfs:/databricks/mlflow/10065689", "experiment_id": "10065689", "lifecycle_stage": "active", "name": "/Users/aaron@databricks.com/Movie Recommendations", "tags": {"mlflow.ownerId": "", "mlflow.experimentType": "NOTEBOOK"}}
{"artifact_location": "dbfs:/databricks/mlflow/12174144", "experiment_id": "12174144", "lifecycle_stage": "active", "name": "/Users/aaron@databricks.com/Basic MLflow", "tags": {"mlflow.ownerId": "", "mlflow.experimentType": "NOTEBOOK"}} …
```
> [PLAT-46718] Export ml experiment

- dbclient/WorkspaceClient.py
- export_db.py
- tasks/tasks.py
- test/thread_safe_writer_test.py
- thread_safe_writer.py
This PR adds ThreadSafeWriter class which ensures thread-safety when writing to a file. This is useful when this Writer object can be used by multiple thread to to execute and write results to a single file without having to worry about race conditions among multiple threads.
This class makes sense to be used when multiple thread writes to a single static file (vs multiple threads write to each different files in which case, we don't need to worry about race conditions from different threads)
In this PR, we make `python3 export_db.py --profile $profile --workspace` use this new class when writing data to 
user_dirs.log,  libraries.log, user_workspace.log files
Testing:
unit test:
```
python3 -m unittest test/thread_safe_writer_test.py
```
manual testing:
Compared the output files after …
> Add thread_safe_writer class

- checkpoint_service.py
- dbclient/MLFlowClient.py
- dbclient/parser.py
- import_db.py
- logging_utils.py
Supports mlflow_experiment import
```
python3 import_db.py --profile mwc_dst --mlflow-experiments --use-checkpoint
```
The command consumes `mlflow_experiments.log` (the output of export_db.py --mlflow-experiments) and creates the experiment objects in the destination workspace. Also it outputs `mlflow_experiments_id_map.log` which has a format of
```
{"old_id": "3825356326110958", "new_id": "2025369099255681"}
{"old_id": "3825356326110957", "new_id": "2025369099255680"}
```
which will be consumed by run import later.
This PR also makes the checkpointer use ThreadSafeWriter
Notes:
- mlflow_experiments_id_map.log only appends instead of rewriting. This is to ensure that upon failures and retries, it still keeps the already imported experiments.
- meaning, one should never remove the …
> Support mlflow_experiment import

- dbclient/WorkspaceClient.py
- export_db.py
- logging_utils.py
https://github.com/databrickslabs/migrate/issues/119
`python3 export_db.py --profile shardqa --export-home kevinkim@databricks.com` works
Also tested for no regression for pipeline workflow:
```
date; time python3 migration_pipeline.py --profile XXX --export-pipeline --use-checkpoint --num-parallel 20 --skip-tasks 'metastore' 'metastore_table_acls'
```
> Fix2 of export-user-home

- dbclient/WorkspaceClient.py
/Shared directory's ACL cannot be modified by design. We should skip /Shared directory when importing the ACL.
```
2022-03-01,15:49:43;WARNING;{"error_code": "INTERNAL_ERROR", "message": "Cannot modify permissions of directory 44857340052148"}
2022-03-01,15:49:43;ERROR;{"error_code": "INTERNAL_ERROR", "message": "Cannot modify permissions of directory 44857340052148", "http_status_code": 500}
```
> skip '/Shared' directories acl

- dbclient/MLFlowClient.py
- dbclient/parser.py
- dbclient/test/MLFlowClientTest.py
- export_db.py
- setup.py
- wmconstants.py
This PR supports the following command:
```
python3 export_db.py --profile dogfood --mlflow-runs --use-checkpoint --num-parallel 8
022-03-08,17:07:00;INFO;Complete MLflow Runs Export Time: 0:07:13.251757
```
Given the scale of the runs (total runs and runs per experimentId. total 220k runs for shard-dogfood), we store the run object data into sqlite. 
Unit test: `python3 -m unittest dbclient/test/MLFlowClientTest.py`
Manual test: 
```
python3 export_db.py --profile dogfood --mlflow-runs --use-checkpoint --num-parallel 1  (take 20 minutes)
python3 export_db.py --profile dogfood --mlflow-runs --use-checkpoint --num-parallel 8 (take 7 minutes)
python3 export_db.py --profile dogfood --mlflow-runs --use-checkpoint --num-parallel 10 (take 5 minutes)
```
Check the total size of the data to make …
> [PLAT-46720] Support mlflow run export

- dbclient/MLFlowClient.py
- dbclient/WorkspaceClient.py
- dbclient/dbclient.py
- dbclient/parser.py
- export_db.py
- import_db.py
- migration_pipeline.py
- test/thread_safe_writer_test.py
- test/threading_utils_test.py
- threading_utils.py
This PR supports http retry logic for making requests to the Databricks API.
The following two command line parameters were added:
```
--retry-total RETRY_TOTAL
Total number or retries when making calls to Databricks API
--retry-backoff RETRY_BACKOFF
Backoff factor to apply between retry attempts when making calls to Databricks API
```
This PR also refactored the code to propagate exceptions that are thrown by threads.
Unit test: `python -m unittest discover -s test -p 'thread*_test.py'`
Manual test of export which successfully exported 90,000 notebooks.
```
date; time python migration_pipeline.py --export-pipeline --profile old --use-checkpoint --debug --num-parallel 20 --retry-total=20 --retry-backoff=1.0 --notebook-format SOURCE --skip-tasks 'metastore' 'metastore_table_acls' 2>&1 | …
```
> [Issue 126] Add http retry logic

- checkpoint_service.py
- dbclient/MLFlowClient.py
- dbclient/parser.py
- dbclient/test/MLFlowClientTest.py
- dbclient/test/TestUtils.py
- export_db.py
- import_db.py
- logging_utils.py
- test/checkpoint/import_mlflow_runs.log
- test/checkpoint_service_test.py
This PR supports ML run import **with artifacts**. 
Workflow:
`python3 import_db.py --profile mwc_dst --src-profile mwc_src --mlflow-runs --use-checkpoint --num-parallel 4` command (note that it requires **--src-profile** flag) does the following:
1. Get all the exported runs from the `mlflow_runs.db` file. (Fetch 10000 runs per time for the sake of memory)
2. For the fetched runs, parallelize and call `self._create_run_and_log` for each of the runs.
==== Parallelize ========
4. `_create_run_and_log` a) creates a run b) log the metrics, params, and tags c) download and upload the run artifact (src_profile is needed for this step)  between a,b, and c steps, we checkpoint the individual operations as well via `steps_checkpointer` (which is different from the master checkpointer)
5. if the …
> [PLAT-46723] ML run import  (with run artifact download and upload)

- dbclient/MLFlowClient.py
- dbclient/dbclient.py
- dbclient/parser.py
- dbclient/test/MLFlowClientTest.py
- dbclient/test/TestUtils.py
- export_db.py
- import_db.py
- wmconstants.py
Support ML experiment permissions export and import
(just review the last commit: https://github.com/databrickslabs/migrate/pull/148/commits/7c11c48ce5d604dee248776120c2c4291a3bd275, since the other commits are handled in other PR)
Testing:
Unit test:
```
python3 -m unittest dbclient/test/MLFlowClientTest.py
```
Export:
```
python3 export_db.py --profile dogfood --mlflow-experiments-permissions --use-checkpoint --num-parallel 10
```
Upon ~4K experiments, it took ~1 minute with 10 threads
```
022-03-23,11:49:01;INFO;Experiment 7118718's experimentType is NOTEBOOK. Only MLFLOW_EXPERIMENT type's permissions are exported. Skipping...
2022-03-23,11:49:01;INFO;Experiment 7138930's experimentType is NOTEBOOK. Only MLFLOW_EXPERIMENT type's permissions are exported. Skipping... …
```
> [PLAT-46719] support experiment permissions (export / import)

- dbclient/MLFlowClient.py
- dbclient/parser.py
- export_db.py
Provides --start-date flag to --mlflow-runs export command line.
With the flag, it will only export the runs that are >= --start-date value.
Confirmed that indeed only the >= start_date runs are exported, by importing the exported runs to dst workspace
```
python3 export_db.py --profile mwc_src --mlflow-runs --start-date 2022-03-24
python3 import_db.py --profile mwc_dst --src-profile mwc_src --mlflow-runs --use-checkpoint --num-parallel 4
```
If the --start-date is not passed, 2015-01-01 is used as default value.
```
python3 export_db.py --profile mwc_src --mlflow-runs
```
Please review the last commit only: https://github.com/databrickslabs/migrate/pull/151/commits/b700f82edae6415a574ee0213b9fe9aa14745aa5
> [PLAT-46721] Export mlflow_runs only start_time >= start-date

- dbclient/WorkspaceClient.py
- import_db.py
- tasks/tasks.py
Databricks ACL teams have reported that parallel import for workspace ACL can cause issues to the backed services. For now, we need to disable parallel feature for workspace ACL import until further scale out / rate limit is implemented in the Databricks backend service.
> Import_workspace_acl should not be called in parallel.

- logging_utils.py
logging.getLogger must be called with different name per object types to make sure the error logs are not streamed to wrong/multiple object error log files.
> Fix get_error_logger

- jumpbox/jumpbox-user-scripts/launch_jumpbox.sh
I was receiving below error(stuck in for loop) when I tried to create a jumpbox using the script:
The config profile (aws-field-eng_databricks-power-user) could not be found Instance i-xxxxxxxxxxx is in Not Ready state. Waiting for the instance to be in running state. Checking again in 5 seconds..
> Using supplied AWS_PROFILE instead of hardcoded value

- README.md
- data/default_jobs_cluster_gcp.json
- data/gcp_cluster.json
- data/gcp_cluster_table_acls.json
- data/workspace_migration_analysis.py
- dbclient/ClustersClient.py
- dbclient/JobsClient.py
- dbclient/dbclient.py
- dbclient/parser.py
- export_db.py
- import_db.py
- migration_pipeline.py
Hi,
I'm including some changes to be able to work with GCP as we have the api's and cli working with GCP (experimental mode). Even that is experimental this will help in the future and also some Databricks gcp customers that needs to migrate assets between different workspaces
The work performed was:
0 - Generate gcp flag
1 - Separate aws, azure and gcp flags (is_aws, is_azure and is_gcp). The logic was looking only for azure flag and if it was null the is_aws was valid. 
I've included the is_azure and is_gcp to remove this logic and is_aws is valid if is_gcp and is azure are null. Maybe in the future include the aws flag is a good option. *TODO*
2 - This allowed to define that if a cluster isn't aws or azure, it will use a gcp template to create a cluster in GCP using the cluster …
> Including --gcp option and updated GCP cluster definitions

- dbclient/JobsClient.py
Fixing [#206 JobsClient does not export tasks for MULTI_TASK jobs](https://github.com/databrickslabs/migrate/issues/206)
The current code is accessing `format` in the root of the response, however the following doc shows `format` is nested in `settings`:
- https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsGet (example response returns `format` in `settings)
Note: The above linked doc is related to API v2.1. However, I tested both v2.0 and v2.1, and both returns `format` in `settings`. (Unfortunately, v2.0 documentation does not mention `format` at all.) 
As reported in the issue, no tasks were returned for MULTI_TASK jobs before. After this change, tasks are returned as expected.
> Fix JobSettings format key

- dbclient/WorkspaceClient.py
- dbclient/dbclient.py
- dbclient/parser.py
- migration_pipeline.py
a few minor improvements:
- added timeout to the REST API calls (observed that the tool may get stuck in some instances)
- added verbose to the pipeline parameters (the code of most classes was already ready for verbose of deeper logs)
- correction to the parent directory creation: should allow not only for `/Repos/<email address>` but also for `/Repos/<arbitrary folder name>`
> chores: added timeout, verbose, repos parent directory

- dbclient/WorkspaceClient.py
Handles the scenario where the source workspace doesn't have any Repo usage. Currently, it fails with the below error.
` 
File "/tmp/git/databricks/migrate/dbclient/WorkspaceClient.py", line 526, in log_all_workspace_items
for repo in repos:
TypeError: 'NoneType' object is not iterable
`
> Handle Empty Repos Scenario

- dbclient/HiveClient.py
When importing metastore, view imports are breaking because view DDLs are updated with a LOCATION section. This make the view definition invalid. This change put in a check and if the DDL is for view, it skips the addition of LOCATION to the DDL.
> Do not update DDL with LOCATION for views

- dbclient/JobsClient.py
The multi-task job tasks may have new_cluster/existing_cluster_id/job_cluster_key for cluster setting. This change fixes cluster adjustment logic to handle import failure with tasks having job_cluster_key.
> Fix for multi-tasks job imports with tasks having job_cluster_key

- dbclient/ClustersClient.py
- migration_pipeline.py
This PR is to support the optional ```driver_instance_pool_id``` attribute that can be present in cluster pool specs.
https://docs.databricks.com/dev-tools/api/latest/clusters.html#request-structure-of-the-cluster-definition
> driver_instance_pool_id : The optional ID of the instance pool to use for the driver node. You must also specify instance_pool_id.
> Instance pool fix for handing driver_instance_pool_id

- README.md
- dbclient/WorkspaceClient.py
- dbclient/common/WorkspaceDiff.py
- dbclient/parser.py
- tasks/tasks.py
Added an option to import notebooks incrementally.
--last-session will define a previous session to compare with the current session. All updated and newly added notebooks will be logged in notebook_changes.log. A set of updated and new notebooks will be created in memory. Only these notebooks will be imported skipping other unchanged notebook.
This is a feature useful when there is a large number of artifacts and we are only interested in importing what has been changed.
> import updated and new notebooks only

- dbclient/WorkspaceClient.py
read_file_changes only when last_session is defined. Otherwise, the pipeline will need to run in a normal mode and import all notebooks.
> fix the issue when there is no notebook_changes.log

- dbclient/WorkspaceClient.py
Improve incremental notebook import by recursively collecting new and updated notebooks in memory first and flush out to logs all together.
This also fixed issue of writing out multiple notebooks in a single line.
> improve incremental notebook import by loading diff in memory and log all together

- dbclient/parser.py
Adding two parameters `--timeout` and ` --skip-missing-users `to the functions `get_export_parser()` and build_client_config(), so the `export_db.py` script + its specific commands can be used. Otherwise, export_db.py errors out because the two parameters are not passed.
> Adding parameters to functions used by export_db.py in parser.py 

- dbclient/JobsClient.py
Problem: continuous (not scheduled) jobs were imported in an UNPAUSED state. 
Fixed this by switching them to a paused state during the import.
> Update JobsClient.py to make sure all jobs are imported as PAUSED

- README.md
- data/notebooks/Import_Table_ACLs_delta.py
- dbclient/HiveClient.py
- dbclient/common/ViewSort.py
- dbclient/parser.py
- tasks/tasks.py
- test/view_sort_test.py
When views are created from other views, we will need to import the parent views first. To resolve this issue, we parse all DDLs of views and create a dependency graph of views. From the graph we will sort the views topologically. The importing process will import the views with that order.
So if view1 is created from view2 and view3, views will be imported in the order of ["view2", "view3", "view1"].
The option --sort-views is added to enable this feature.
> Sort views topologically before importing

- docker/README.md
- docker/databricks/.databrickscfg
- docker/dockerfile
As the title reads, leveraging Docker to package the migrate utility for use in Windows and (potentially) other OS environments.
> adding Docker packaging to support non-linux/macOS environments

- dbclient/common/WorkspaceDiff.py
When comparing new exported artifacts with the previous one, we were only add changed files from subdirectories. This fix will add individual files in the current directory to the change list as well.
An unused function log_updated_new_files() is removed.
> Bug fix for incremental notebook import

- dbclient/HiveClient.py
Not sure if there is an underlying reason for the current logic, but I believe that checkpoints should not be added, if an error response is received when applying the ddl for a view.
> Fix checkpoint logic for views
